apiVersion: v1
kind: Pod
metadata:
  name: unito-uc3
spec:
  restartPolicy: Never
  containers:
    - name: dh
      image: perlodaniele/dh-base:latest
      env:
        - name: WANDB_BASE_URL
          valueFrom:
            secretKeyRef:
              name: my-wandb-auth #dummy references
              key: host
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-wandb-auth
              key: key
      command: ["tail", "-f", "/dev/null"] #change with the commands you want to run
      resources:
        limits:
          nvidia.com/gpu: 4
        requests:
          nvidia.com/gpu: 4
      volumeMounts:
        - name: uc3-data #this is just a local name
          mountPath: /mnt/data
        - name: shm
          mountPath: /dev/shm
  volumes:
    - name: uc3-data
      persistentVolumeClaim:
        claimName: uc3-volume
    - name: shm
      emptyDir:
        medium: Memory
